GET http://localhost:3000

GET http://localhost:3000/auth/financial-data?fleetNumber=FLEET123

#### Login Route 

POST http://localhost:3000/auth/login



#### Register route 
POST http://localhost:3000/auth/register

Content-Type: application/json

{
  "email": "example@gmail.com",
  "password": "examplePassword123",
  "fleetNumber":"FLEET123"
}

#### Refresh Route
POST http://localhost:3000/auth/refresh-token


#### Logout Route
DELETE  http://localhost:3000/auth/logout

# register a bus
POST http://localhost:3000/matatu/register
Content-Type: application/json
{
  "fleetNumber": "FLEET1124",
  "numberPlate": "KAA153B",
  "sacco":"Umo Inner",
  "image":"https://i0.wp.com/www.safari254.com/wp-content/uploads/2016/05/Matatus_manyanga.jpg"
}


# Making a Mpesa Payment
POST http://localhost:3000/payment/mpesa

{
  "fleetNumber": "FLEET123",
  "numberPlate":"KAA123A",
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phoneNumber": "254712345678",
  "amount": "100"
}


GET http://localhost:3000/dashboard?fleetNumber=FLEET123





